export const contactsNetworkData = [{
  img: "/images/ntf-1.svg",
  name: "@MisterTea5",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:true,
  invite:false,
},
{
  img: "/images/ntf-2.png",
  name: "@Shaquille.oatmeal",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-3.png",
  name: "@Hoosier-daddy",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-4.png",
  name: "@BadKarma",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-5.png",
  name: "@Casanova",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-6.png",
  name: "@MisterTea5",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:true,
},
{
  img: "/images/ntf-7.png",
  name: "@HairyPoppins",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-8.png",
  name: "@YellowSnowman",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-9.png",
  name: "@Tinfoilhat",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-10.png",
  name: "@HeartTicker",  
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-11.png",
  name: "@PawneeGoddess",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
},
{
  img: "/images/ntf-12.png",
  name: "@Babushka",
  dec: "NFT Community and Metaverse. Follow and ...",
  date: "July 15",
  msg:false,
  invite:false,
}
]
